services:
  - type: web
    name: yumeflower-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: TG_BOT_TOKEN
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DATABASE_URL
        sync: false
